#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : testBD.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Dec 01 18:59:08 CET 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved. 
#
# usage: testBD.sh [-help]
# usage: testBD.sh [-lib_map_path]
# usage: testBD.sh [-noclean_files]
# usage: testBD.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'testBD.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib axi_infrastructure_v1_1_0 axi_vip_v1_1_10 processing_system7_vip_v1_0_12 generic_baseblocks_v2_1_0 fifo_generator_v13_2_5 axi_data_fifo_v2_1_23 axi_register_slice_v2_1_24 axi_protocol_converter_v2_1_24 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "testBD.sh - Script generated by export_simulation (Vivado v2021.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/testBD/ipshared/bbf0/hdl/AES256_encrypt_IP_v1_0_S00_AXI.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/testBD/ipshared/bbf0/src/AES256_enc_FSM_AXI.sv" \
    "$ref_dir/../../../bd/testBD/ipshared/bbf0/src/mod_demuxInit.sv" \
    "$ref_dir/../../../bd/testBD/ipshared/bbf0/src/mod_enc_addRoundKey.sv" \
    "$ref_dir/../../../bd/testBD/ipshared/bbf0/src/mod_enc_mixColumns.sv" \
    "$ref_dir/../../../bd/testBD/ipshared/bbf0/src/mod_enc_rom256.sv" \
    "$ref_dir/../../../bd/testBD/ipshared/bbf0/src/mod_enc_shifter.sv" \
    "$ref_dir/../../../bd/testBD/ipshared/bbf0/src/mod_mux_2to1.sv" \
    "$ref_dir/../../../bd/testBD/ipshared/bbf0/src/mod_reg16.sv" \
    "$ref_dir/../../../bd/testBD/ipshared/bbf0/src/mod_reg16_16to1_HZ.sv" \
    "$ref_dir/../../../bd/testBD/ipshared/bbf0/src/mod_reg16_4to16_INIT.sv" \
    "$ref_dir/../../../bd/testBD/ipshared/bbf0/src/mod_romKey.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/testBD/ipshared/bbf0/hdl/AES256_encrypt_IP_v1_0.v" \
    "$ref_dir/../../../bd/testBD/ip/testBD_AES256_encrypt_IP_0_0/sim/testBD_AES256_encrypt_IP_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/0980/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_12 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/testBD/ip/testBD_processing_system7_0_0/sim/testBD_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/94ec/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_24 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/8f68/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_24 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/6e0d/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/testBD/ip/testBD_auto_pc_0/sim/testBD_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/testBD/ip/testBD_rst_ps7_0_50M_0/sim/testBD_rst_ps7_0_50M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../testBlockDesign.gen/sources_1/bd/testBD/ipshared/f42d/hdl" +incdir+"/opt/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/testBD/sim/testBD.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.testBD xil_defaultlib.glbl -o testBD_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./testBD_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./testBD.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/adrian/Desktop/AES256-HW-Accelerator/Vivado_projects/testBlockDesign/testBlockDesign.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key testBD_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc testBD_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./testBD.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: testBD.sh [-help]\n\
Usage: testBD.sh [-lib_map_path]\n\
Usage: testBD.sh [-reset_run]\n\
Usage: testBD.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
