#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Sep 18 18:48:51 CEST 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto efdbea65d14a44c1b3e0c54473ec19e1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_mod_enc_shifter_behav xil_defaultlib.tb_mod_enc_shifter xil_defaultlib.glbl -log elaborate.log"
xelab -wto efdbea65d14a44c1b3e0c54473ec19e1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_mod_enc_shifter_behav xil_defaultlib.tb_mod_enc_shifter xil_defaultlib.glbl -log elaborate.log

