# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/GPIO_Constraints_design6.xdc

# Block Designs: bd/AES256_system_design6/AES256_system_design6.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES256_system_design6 || ORIG_REF_NAME==AES256_system_design6} -quiet] -quiet

# IP: bd/AES256_system_design6/ip/AES256_system_design6_processing_system7_0_0/AES256_system_design6_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES256_system_design6_processing_system7_0_0 || ORIG_REF_NAME==AES256_system_design6_processing_system7_0_0} -quiet] -quiet

# IP: bd/AES256_system_design6/ip/AES256_system_design6_axi_gpio_0_0/AES256_system_design6_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES256_system_design6_axi_gpio_0_0 || ORIG_REF_NAME==AES256_system_design6_axi_gpio_0_0} -quiet] -quiet

# IP: bd/AES256_system_design6/ip/AES256_system_design6_axi_timer_0_0/AES256_system_design6_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES256_system_design6_axi_timer_0_0 || ORIG_REF_NAME==AES256_system_design6_axi_timer_0_0} -quiet] -quiet

# IP: bd/AES256_system_design6/ip/AES256_system_design6_xbar_0/AES256_system_design6_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES256_system_design6_xbar_0 || ORIG_REF_NAME==AES256_system_design6_xbar_0} -quiet] -quiet

# IP: bd/AES256_system_design6/ip/AES256_system_design6_ps7_0_axi_periph_0/AES256_system_design6_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES256_system_design6_ps7_0_axi_periph_0 || ORIG_REF_NAME==AES256_system_design6_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AES256_system_design6/ip/AES256_system_design6_rst_ps7_0_50M_0/AES256_system_design6_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES256_system_design6_rst_ps7_0_50M_0 || ORIG_REF_NAME==AES256_system_design6_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/AES256_system_design6/ip/AES256_system_design6_AES256_device_IP_0_0/AES256_system_design6_AES256_device_IP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES256_system_design6_AES256_device_IP_0_0 || ORIG_REF_NAME==AES256_system_design6_AES256_device_IP_0_0} -quiet] -quiet

# IP: bd/AES256_system_design6/ip/AES256_system_design6_auto_pc_0/AES256_system_design6_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES256_system_design6_auto_pc_0 || ORIG_REF_NAME==AES256_system_design6_auto_pc_0} -quiet] -quiet

# XDC: /home/adrian/Desktop/AES256-HW-Accelerator/Vivado_projects/AES256_system/AES256_system.gen/sources_1/bd/AES256_system_design6/AES256_system_design6_ooc.xdc
