# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adrian/Desktop/AES256-HW-Accelerator/Vivado_projects/AES256_system/AES256_system.srcs/sources_1/bd/AES256_system_design6/ip/AES256_system_design6_xbar_0/AES256_system_design6_xbar_0.xci
# IP: The module: 'AES256_system_design6_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adrian/Desktop/AES256-HW-Accelerator/Vivado_projects/AES256_system/AES256_system.gen/sources_1/bd/AES256_system_design6/ip/AES256_system_design6_xbar_0/AES256_system_design6_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES256_system_design6_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/adrian/Desktop/AES256-HW-Accelerator/Vivado_projects/AES256_system/AES256_system.srcs/sources_1/bd/AES256_system_design6/ip/AES256_system_design6_xbar_0/AES256_system_design6_xbar_0.xci
# IP: The module: 'AES256_system_design6_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adrian/Desktop/AES256-HW-Accelerator/Vivado_projects/AES256_system/AES256_system.gen/sources_1/bd/AES256_system_design6/ip/AES256_system_design6_xbar_0/AES256_system_design6_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES256_system_design6_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
