# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adrian/Desktop/AES256-HW-Accelerator/Vivado_projects/testBlockDesign/testBlockDesign.srcs/sources_1/bd/testBD/ip/testBD_rst_ps7_0_50M_0/testBD_rst_ps7_0_50M_0.xci
# IP: The module: 'testBD_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adrian/Desktop/AES256-HW-Accelerator/Vivado_projects/testBlockDesign/testBlockDesign.gen/sources_1/bd/testBD/ip/testBD_rst_ps7_0_50M_0/testBD_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'testBD_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/adrian/Desktop/AES256-HW-Accelerator/Vivado_projects/testBlockDesign/testBlockDesign.gen/sources_1/bd/testBD/ip/testBD_rst_ps7_0_50M_0/testBD_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'testBD_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/adrian/Desktop/AES256-HW-Accelerator/Vivado_projects/testBlockDesign/testBlockDesign.gen/sources_1/bd/testBD/ip/testBD_rst_ps7_0_50M_0/testBD_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'testBD_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/adrian/Desktop/AES256-HW-Accelerator/Vivado_projects/testBlockDesign/testBlockDesign.srcs/sources_1/bd/testBD/ip/testBD_rst_ps7_0_50M_0/testBD_rst_ps7_0_50M_0.xci
# IP: The module: 'testBD_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adrian/Desktop/AES256-HW-Accelerator/Vivado_projects/testBlockDesign/testBlockDesign.gen/sources_1/bd/testBD/ip/testBD_rst_ps7_0_50M_0/testBD_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'testBD_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/adrian/Desktop/AES256-HW-Accelerator/Vivado_projects/testBlockDesign/testBlockDesign.gen/sources_1/bd/testBD/ip/testBD_rst_ps7_0_50M_0/testBD_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'testBD_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/adrian/Desktop/AES256-HW-Accelerator/Vivado_projects/testBlockDesign/testBlockDesign.gen/sources_1/bd/testBD/ip/testBD_rst_ps7_0_50M_0/testBD_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'testBD_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
