#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Jan 25 21:39:35 CET 2022
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 34312ca27ac84deeb6df16960aa62e0c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_mod_fifo_1to4_behav xil_defaultlib.tb_mod_fifo_1to4 xil_defaultlib.glbl -log elaborate.log"
xelab -wto 34312ca27ac84deeb6df16960aa62e0c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_mod_fifo_1to4_behav xil_defaultlib.tb_mod_fifo_1to4 xil_defaultlib.glbl -log elaborate.log

