# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/prueba_bd/prueba_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_bd || ORIG_REF_NAME==prueba_bd} -quiet] -quiet

# IP: bd/prueba_bd/ip/prueba_bd_processing_system7_0_0/prueba_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_bd_processing_system7_0_0 || ORIG_REF_NAME==prueba_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/prueba_bd/ip/prueba_bd_ps7_0_axi_periph_0/prueba_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==prueba_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/prueba_bd/ip/prueba_bd_rst_ps7_0_50M_0/prueba_bd_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==prueba_bd_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/prueba_bd/ip/prueba_bd_ila_0_0/prueba_bd_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_bd_ila_0_0 || ORIG_REF_NAME==prueba_bd_ila_0_0} -quiet] -quiet

# IP: bd/prueba_bd/ip/prueba_bd_ila_1_0/prueba_bd_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_bd_ila_1_0 || ORIG_REF_NAME==prueba_bd_ila_1_0} -quiet] -quiet

# IP: bd/prueba_bd/ip/prueba_bd_xbar_0/prueba_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_bd_xbar_0 || ORIG_REF_NAME==prueba_bd_xbar_0} -quiet] -quiet

# IP: bd/prueba_bd/ip/prueba_bd_AES256_v2_0_1/prueba_bd_AES256_v2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_bd_AES256_v2_0_1 || ORIG_REF_NAME==prueba_bd_AES256_v2_0_1} -quiet] -quiet

# IP: bd/prueba_bd/ip/prueba_bd_auto_pc_0/prueba_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_bd_auto_pc_0 || ORIG_REF_NAME==prueba_bd_auto_pc_0} -quiet] -quiet

# XDC: bd/prueba_bd/prueba_bd_ooc.xdc
