# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/prueba1/prueba1.srcs/sources_1/bd/prueba_bd/ip/prueba_bd_xbar_0/prueba_bd_xbar_0.xci
# IP: The module: 'prueba_bd_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/prueba1/prueba1.srcs/sources_1/bd/prueba_bd/ip/prueba_bd_xbar_0/prueba_bd_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prueba_bd_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/prueba1/prueba1.srcs/sources_1/bd/prueba_bd/ip/prueba_bd_xbar_0/prueba_bd_xbar_0.xci
# IP: The module: 'prueba_bd_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/prueba1/prueba1.srcs/sources_1/bd/prueba_bd/ip/prueba_bd_xbar_0/prueba_bd_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prueba_bd_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
