#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Sep 04 12:55:02 CEST 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto c376b30b35c74caf9a73d2b4e91c99e6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_mod_regCTRL_behav xil_defaultlib.tb_mod_regCTRL xil_defaultlib.glbl -log elaborate.log"
xelab -wto c376b30b35c74caf9a73d2b4e91c99e6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_mod_regCTRL_behav xil_defaultlib.tb_mod_regCTRL xil_defaultlib.glbl -log elaborate.log

