# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "c:/users/rmartinez/projects/riscv/proyectoadrin/vivado/prueba1/prueba1.tmp/aes256_v2_v1_0_project/AES256_v2_v1_0_project.runs/synth_1/AES256_v2_v1_0.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 2
set_param synth.incrementalSynthesisCache C:/Users/RMartinez/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-4624-pc6253/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/rmartinez/projects/riscv/proyectoadrin/vivado/prueba1/prueba1.tmp/aes256_v2_v1_0_project/AES256_v2_v1_0_project.cache/wt [current_project]
set_property parent.project_path c:/users/rmartinez/projects/riscv/proyectoadrin/vivado/prueba1/prueba1.tmp/aes256_v2_v1_0_project/AES256_v2_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.4 [current_project]
set_property ip_repo_paths {
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/testip_1.0
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/aes_256_1.0
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/users/rmartinez/projects/riscv/proyectoadrin/vivado/prueba1/prueba1.tmp/aes256_v2_v1_0_project/AES256_v2_v1_0_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library "" -sv {
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/AES256_dec_FSM_AXI.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/AES256_device_FSM_AXI.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/AES256_enc_FSM_AXI.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/AES256_keygen_FSM_AXI.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/fifo_128_32.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_dec_addRoundKey.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_dec_mixColumns.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_dec_rom256.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_dec_shifter.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_enc_addRoundKey.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_enc_mixColumns.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_enc_rom256.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_enc_shifter.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_fifo_1to4.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/verilogCode/design/mod_fifo_1to8.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_kg_rotWord.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_kg_subWord.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_mux_2to1.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_reg16.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_reg16_16to1.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_reg16_1to16.sv
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/src/mod_romKey.sv
}
read_verilog -library "" {
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/hdl/AES256_v2_v1_0_S00_AXI.v
  c:/Users/RMartinez/Projects/RiscV/ProyectoAdrin/vivado/ip_repo/AES256_v2_1.0/hdl/AES256_v2_v1_0.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top AES256_v2_v1_0 -part xc7z020clg484-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef AES256_v2_v1_0.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file AES256_v2_v1_0_utilization_synth.rpt -pb AES256_v2_v1_0_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
